general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    brightness = 0.7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    outer_color = rgba(117, 241, 250, 1.0)
    inner_color = rgba(24, 24, 27, 0.9)
    font_color = rgba(255, 255, 255, 1.0)

    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>

    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(255, 255, 255, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font

    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %d %B  %I:%M %p')"
    color = rgba(255, 255, 255, 0.9)
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, 140
    halign = center
    valign = center
}